[project]
name = "argocd-lab-backend"
version = "0.1.0"
description = "Simple FastAPI ping service"
readme = "README.md"
requires-python = "==3.14.2"

dependencies = [
  "fastapi>=0.115.2",
  "uvicorn[standard]>=0.32.0",
]

[tool.uv]
index-url = "https://pypi.org/simple"
