apiVersion: v2
name: postgres
description: PostgreSQL database for Airflow
type: application
version: 1.0.0
appVersion: "16"
dependencies:
  - name: postgresql
    version: 16.5.0
    repository: https://charts.bitnami.com/bitnami
