apiVersion: v2
name: airflow
description: Apache Airflow with external PostgreSQL
type: application
version: 1.0.0
appVersion: "3.0.2"
dependencies:
  - name: airflow
    version: 1.18.0
    repository: https://airflow.apache.org
